myBlog/blog/urls.py
from django.conf.urls import url, include
from . import views

# 设置应用命名空间
app_name = 'blog'


# 配置应用url
urlpatterns = [
    url('^$', views.index, name='index'),
    url('^login/$', views.login, name='login'),
    url('^(\d+)/$', views.index, name='index'),
    url('^full_width/(\d+)/$', views.full_width, name='full_width'),
    url('^single/(\d+)/$', views.single, name='single'),
    url('^comment/(\d+)/$', views.comment, name='comment'),
    url('^kind/(\d+)/(\d+)/$', views.article_kind, name='article_kind'),
    url('^tag/(\d+)/(\d+)/$', views.article_tag, name='article_tag'),
    url('^file/(\d+)/(\d{4})/(\d{1})/$', views.article_date, name='article_date'),
]

myBlog/myBlog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from haystack.views import SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^$', views.index),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    # 全文搜索
    url(r'^search/', SearchView(), name='search'),
]

myBlog/blog/models.py
from django.db import models

# Create your models here.


class UserManager(models.Manager):
    """
    用户管理类
    """
    def create_user(self, account, password):
        user = self.model()
        user.account = account
        user.password = password
        return user

    def create_save_user(self, account, password):
        user = self.create(account=account, password=password)
        return user


class ArticleManager(models.Manager):
    """
    文章管理类
    """
    def create_article(self, title, content):
        article = self.model()
        article.title = title
        article.content = content
        return article

    def create_save_article(self, title, content):
        article = self.create(title=title, content=content)
        return article


class ArticleTagManager(models.Manager):
    """
    标签云管理类
    """
    def create_tag(self, name, article):
        tag = self.model()
        tag.name = name
        tag.article = article
        return tag

    def create_save_tag(self, name, article):
        return self.create(name=name, article=article)


class ArticleKindManager(models.Manager):
    """
    文章管理类
    """
    def create_kind(self, name):
        article_kind = self.model()
        article_kind.name = name
        return article_kind

    def create_save_kind(self, name):
        return self.create(name=name)


class User(models.Model):
    """
        创建用户表，继承model下的Model类，该类提供了与数据库交互的所有方法
    """

    # 构建字段,用户账号
    account = models.CharField(max_length=20, unique=True)
    # 用户密码
    password = models.CharField(max_length=30)
    # 用户昵称
    nickname = models.CharField(max_length=20, default="新用户")
    # 用户邮箱
    email = models.CharField(max_length=30, default="待完善")
    # 性别
    gender = models.BooleanField()
    # 年龄
    age = models.IntegerField(default=0)
    # 用户积分
    integral = models.IntegerField(default=100)
    # 用户说明
    describe = models.CharField(max_length=255,  default="暂无说明")
    # 注册时间
    register_time = models.DateTimeField(auto_now_add=True)
    # 是否激活
    is_delete = models.BooleanField(default=False)
    # 用户管理类
    manager = UserManager()

    def __str__(self):
        return self.account

    def show_account(self):
        return self.account
    show_account.short_description = "账号"

    def show_nickname(self):
        return self.nickname
    show_nickname.short_description = "昵称"

    def show_email(self):
        return self.email
    show_email.short_description = "邮箱"

    def show_integral(self):
        return self.integral
    show_integral.short_description = "积分"

    def show_register_time(self):
        return self.register_time
    show_register_time.short_description = "注册时间"


class Article(models.Model):
    """
        构建文章对象
    """
    # 标题
    title = models.CharField(max_length=30)
    # 摘要
    abstract = models.CharField(max_length=255)
    # 内容
    content = models.TextField()
    # 阅读次数
    read_count = models.IntegerField(default=0)
    # 评论数
    comment_count = models.IntegerField(default=0)
    # 发布日期
    publish_date = models.DateField(auto_now_add=True)
    # 发布时间
    publish_time = models.DateTimeField(auto_now_add=True)
    # 修改
    modified_time = models.DateTimeField(auto_now=True)
    # 所属用户
    user = models.ForeignKey("User", on_delete=models.CASCADE)
    # 类型
    kind = models.ForeignKey("ArticleKind", on_delete=models.CASCADE)
    manager = ArticleKindManager()

    def show_title(self):
        return self.title
    show_title.short_description = "标题"

    def show_read_count(self):
        return self.read_count
    show_read_count.short_description = "浏览次数"

    def show_publish_time(self):
        return self.publish_time
    show_publish_time.short_description = "发布时间"

    def __str__(self):
        return self.title


class ArticleTag(models.Model):
    # 标签名
    name = models.CharField(max_length=20)
    # 标签总数
    count = models.IntegerField(default=0)
    # 文章
    article = models.ManyToManyField(to="Article", null=True, blank=True)
    manager = ArticleTagManager()

    def __str__(self):
        return self.name


class ArticleKind(models.Model):
    # 文章种类名
    name = models.CharField(max_length=20)
    # 该种类文章数量
    count = models.IntegerField(default=0)
    manager = ArticleKindManager()

    def __str__(self):
        return self.name

myBlog/blog/forms.py
from .models import *
from django import forms


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['account', 'password', 'nickname', 'email', 'gender', 'age', 'integral', 'describe']
        labels = {
            'account': '账号',
            'password': '密码',
            'nickname': '昵称',
            'email': '邮箱',
            'gender': '性别',
            'age': '年龄',
            'integral': '积分',
            'describe': '个人简介',
        }
        widgets = {
            'password': forms.widgets.PasswordInput()
        }

myBlog/blog/views.py
from django.shortcuts import render, redirect
from comment.forms import CommentForm
from django.http import HttpResponse
from django.core.paginator import Paginator, Page
from . import forms
from .models import *

import markdown

# Create your views here.


def login(request):
    """
    用户登陆界面
    :param request:
    :return:
    """
    if request.method == "GET":
        form = forms.UserForm()
        return render(request, 'blog/login.html', context={'form': form})

    elif request.method == "POST":
        request.session['account'] = request.POST.get('account')
        return redirect('/blog/1')


def index(request, page):
    """
    系统主页
    :param request:
    :return:
    """
    page = request.GET.get('page')
    page = page if page else 1
    # 获取所有文章
    articles = Article.manager.all()
    paginator = Paginator(articles, 2)

    page = paginator.page(page)

    # count = articles.count()
    # page_count = count//3 + 1
    # if page > page_count:
    #     return render(request, 'blog/index.html', context={'articles': articles, 'current_page': 1})
    #
    # if count <= 3:
    #     return render(request, 'blog/index.html', context={'articles': articles, 'current_page': 1, 'page': page})
    #
    # articles = articles[(page-1)*3:page*3]
    # pages = [x+1 for x in range(page_count)]
    return render(request, 'blog/index.html', context={'articles': articles, 'current_page': 1, 'page': page})


def full_width(request, page):
    page = int(page)
    count = Article.manager.all().count()
    if count <= 10:
        articles = Article.manager.all()
        return render(request, 'blog/full-width.html',
                      context={'articles': articles})
    else:
        page_count = count // 10 + 1
        if page > page_count:
            return HttpResponse('该页面不存在')
        else:
            articles = Article.manager.all()[(page - 1) * 10:page * 10]
            pages = [x + 1 for x in range(page_count)]
            return render(request, 'blog/full-width.html', context={'articles': articles})


def single(request, aid):
    article = Article.manager.all().filter(pk=aid).first()
    if request.method == "GET":
        form = CommentForm()
        article.read_count += 1
        article.save()
        return render(request, 'blog/single.html', context={'article': article, 'form': form})
    elif request.method == "POST":
        return render(request, 'blog/single.html', context={'article': article})


def comment(request, aid):
    """
    评论处理
    :param request:
    :return:
    """
    article = Article.manager.all().filter(pk=aid).first()
    if request.method == "GET":
        form = CommentForm()
        article.read_count += 1
        return render(request, 'blog/single.html', context={'article': article, 'form': form})
    elif request.method == "POST":
        comment = CommentForm(request.POST)
        if comment.is_valid():
            comment = comment.save(commit=False)
            comment.user = User.manager.all().filter(account=request.session.get("account")).first()
            comment.article = Article.manager.all().filter(pk=aid).first()
            comment.article.comment_count += 1
            comment.article.save()
            comment.save()
            return redirect('/blog/single/%s' % aid)
        else:
            return HttpResponse("该页面不存在")


def article_kind(request, page, kid):
    """
    文章分类
    :param request:
    :param page:
    :param kind:
    :return:
    """
    page = int(page)
    # 获取所有文章
    articles = Article.manager.all().filter(kind=kid)
    count = articles.count()
    if count <= 3:
        return render(request, 'blog/index.html', context={'articles': articles, 'current_page': page})
    else:
        page_count = count//3 + 1
        if page > page_count:
            return HttpResponse('该页面不存在')
        else:
            articles = Article.manager.all().filter(kind=kid)[(page-1)*3:page*3]
            pages = [x+1 for x in range(page_count)]
            return render(request, 'blog/index.html', context={'articles': articles, 'pages': pages, 'current_page': page})


def article_tag(request, page, tid):
    """
    文章分类
    :param request:
    :param page:
    :param kind:
    :return:
    """
    page = int(page)
    # 获取所有文章
    articles = ArticleTag.manager.all().filter(pk=tid).first().article.all()
    count = articles.count()
    if count <= 3:
        return render(request, 'blog/index.html', context={'articles': articles, 'current_page': page})
    else:
        page_count = count//3 + 1
        if page > page_count:
            return HttpResponse('该页面不存在')
        else:
            articles = articles[(page-1)*3:page*3]
            pages = [x+1 for x in range(page_count)]
            return render(request, 'blog/index.html', context={'articles': articles, 'pages': pages, 'current_page': page})


def article_date(request, page, year, month):
    page = int(page)
    # 获取所有文章

    articles = Article.manager.all().filter(publish_date__year=year).filter(publish_date__month=month)
    count = articles.count()
    if count <= 3:
        return render(request, 'blog/index.html', context={'articles': articles, 'current_page': page})
    else:
        page_count = count//3 + 1
        if page > page_count:
            return HttpResponse('该页面不存在')
        else:
            articles = articles[(page-1)*3:page*3]
            pages = [x+1 for x in range(page_count)]
            return render(request, 'blog/index.html', context={'articles': articles, 'pages': pages, 'current_page': page})


def filter_index_articles(request, articles, page=1):
    count = articles.count()
    page_count = count//3 + 1
    if page > page_count:
        return render(request, 'blog/index.html', context={'articles': articles, 'current_page': 1})

    if count <= 3:
        return render(request, 'blog/index.html', context={'articles': articles, 'current_page': page})

    articles = articles[(page-1)*3:page*3]
    pages = [x+1 for x in range(page_count)]
    return render(request, 'blog/index.html', context={'articles': articles, 'pages': pages, 'current_page': page})

myBlog/templates/blog/base.html
<!DOCTYPE html>
{% load extend_tag %}
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="/static/blog/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="/static/blog/css/pace.css">
    <link rel="stylesheet" href="/static/blog/css/custom.css">

    <!-- js -->
    <script src="/static/blog/js/jquery-2.1.3.min.js"></script>
    <script src="/static/blog/js/bootstrap.min.js"></script>
    <script src="/static/blog/js/pace.min.js"></script>
    <script src="/static/blog/js/modernizr.custom.js"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        {% block header %}
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' 1%}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:full_width' 1%}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="/search/">
                            <input type="search" placeholder="搜索" required name="q">
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
        {% endblock %}
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="http://zmrenwu.com/">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            {% block main %}
            <main class="col-md-8">
                {% for article in articles %}
                    <article class="post post-1">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{% url 'blog:single' article.id%}">{{article.title}}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="#">{{article.kind}}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="2012-11-09T23:15:57+00:00">{{article.publish_date}}</time></a></span>
                            <span class="post-author"><a href="#">{{article.user.nickname}}</a></span>
                            <span class="comments-link"><a href="#">{{article.comment_count}} 评论</a></span>
                            <span class="views-count"><a href="#">{{article.read_count}} 阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{{article.content}}</p>
                        <div class="read-more cl-effect-14">
                            <a href="{% url 'blog:single' article.id %}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
                </article>
                {% empty %}
                    <div>当前没有任何文章</div>
                {% endfor %}

                <div class="pagination">
                    <ul>
                        {% if page.has_previous %}
                            <a href="?page={{page.number|add:-1}}">上一页</a>
                        {% endif %}
                        {% for p in page.paginator.page_range %}
                            {% if page.number == p %}
                                <li class="current"><a href="" >{{p}}</a></li>
                            {% else %}
                                <li><a href="?page={{p}}" >{{p}}</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if page.has_next %}
                            <a href="?page={{page.number|add:1}}">下一页</a>
                        {% endif %}
                    </ul>
                </div>
            </main>
            {% endblock %}
            <aside class="col-md-4">
                <div class="widget widget-content">
                    {% block catalog %}
                    {% endblock %}
                </div>
                <div class="widget widget-recent-posts">

                    {% block newarticle %}
                    <h3 class="widget-title">最新文章</h3>
                    <ul>
                        {% getNewArticles as newArticles %}
                        {% for article in newArticles %}
                            <li>
                                <a href="{% url 'blog:single' article.id %}">{{article.title}}</a>
                            </li>
                        {% empty %}
                            最近没有文章
                        {% endfor %}
                    </ul>
                    {% endblock %}
                </div>
                <div class="widget widget-archives">
                    {% block monthfile %}
                    <h3 class="widget-title">归档</h3>
                    <ul>
                        {% getArticleMonth as articleMonth %}
                        {% for date in articleMonth %}
                            <li>
                                <a href="{% url 'blog:article_date' 1  date.year date.month %}">{{date.year}}年 {{date.month}}月</a>
                            </li>
                        {% empty %}
                            没有文件
                        {% endfor %}
                    </ul>
                    {% endblock %}
                </div>

                <div class="widget widget-category">
                    {% block kind %}
                    <h3 class="widget-title">分类</h3>
                    <ul>
                        {% getArticleKind as articleKind %}
                        {% for kind in articleKind %}
                            <li>
                                <a href="{% url 'blog:article_kind' 1  kind.id %}">{{kind.name}} <span class="post-count">({{kind.count}})</span></a>
                            </li>
                        {% empty %}
                            没有分类
                        {% endfor %}
                    </ul>
                    {% endblock %}
                </div>

                <div class="widget widget-tag-cloud">
                    {% block tag %}
                    <h3 class="widget-title">标签云</h3>
                    <ul>
                        {% getArticleTag as articleTag %}
                        {% for tag in articleTag %}
                            <li>
                                <a href="{% url 'blog:article_tag' 1  tag.id %}">{{tag.name}}</a>
                            </li>
                        {% empty %}
                            没有标签
                        {% endfor %}
                    </ul>
                    {% endblock %}
                </div>
                <div class="rss">
                    {% block RSS %}
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                    {% endblock %}
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    {% block footer %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
    {% endblock %}
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    {% block menu %}
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
    {% endblock %}
</div>

<script src="/static/blog/js/script.js"></script>

</body>
</html>

myBlog/templates/blog/full-width.html
{% extends 'blog/base.html' %}
{% block main %}

    <main class="col-md-12">
    {% for article in articles %}
    <article class="post post-1">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{% url 'blog:single' article.id%}">{{article.title}}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{article.kind}}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="2012-11-09T23:15:57+00:00">{{article.publish_date}}</time></a></span>
            <span class="post-author"><a href="#">{{article.user.nickname}}</a></span>
            <span class="comments-link"><a href="#">{{article.comment_count}} 评论</a></span>
            <span class="views-count"><a href="#">{{article.read_count}} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <p>{{article.content}}</p>
        <div class="read-more cl-effect-14">
            <a href="{% url 'blog:single' article.id%}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
        </div>
    </div>
    </article>
    {% empty %}
    <div>当前没有任何文章</div>
    {% endfor %}
    </main>
{% endblock %}
{% block newarticle %}  {% endblock %}
{% block monthfile %}  {% endblock %}
{% block kind %}  {% endblock %}
{% block tag %}  {% endblock %}
{% block RSS %}  {% endblock %}
{% block footer %}  {% endblock %}
{% block menu %}  {% endblock %}

myBlog/templates/blog/index.html
{% extends 'blog/base.html' %}

myBlog/templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登陆界面</title>
</head>
<body>
    <div class="login_form" style="width: 600px; margin: auto">
        <a href=""><h1>用户登陆</h1></a>
        <form action="{% url 'blog:login' %}" method="post">
            {% csrf_token %}
            账号：<span style="display: inline-block; height: 40px">{{form.account}}</span> <br>
            密码：<span style="display: inline-block; height: 40px">{{form.password}}</span> <br>
            <input type="submit">
        </form>
    </div>
</body>
</html>

myBlog/templates/blog/single.html
{% extends 'blog/base.html' %}
{% load extend_tag %}
{% block catalog %}
    <h3 class="widget-title">文章目录</h3>
    <ul>
        <li>
            <a href="#">教程特点</a>
        </li>
        <li>
            <a href="#">谁适合这个教程</a>
        </li>
        <li>
            <a href="#">在线预览</a>
        </li>
        <li>
            <a href="#">资源列表</a>
        </li>
        <li>
            <a href="#">获取帮助</a>
        </li>
    </ul>
{% endblock %}
{% block main %}
    <main class="col-md-8">
        <article class="post post-1">
            <header class="entry-header">
                <h1 class="entry-title">{{article.title}}</h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="#">{{article.kind}}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date"
                                                              datetime="2012-11-09T23:15:57+00:00">2017年5月11日</time></a></span>
                    <span class="post-author"><a href="#">{{article.user.nickname}}</a></span>
                    <span class="comments-link"><a href="#">{{article.comment_count}} 评论</a></span>
                    <span class="views-count"><a href="#">{{article.read_count}} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>Django 是使用 Python 编写的一个开源 Web 框架，可以用来快速搭建一个高性能的网站。</p>
                <blockquote><p>Django makes it easier to build better Web apps more quickly and with less
                    code.</p>
                    <p>Django 让你以更快的速度、更少的代码、更轻松的方式搭建更好的 Web 应用。</p>
                </blockquote>
                <p>本教程将带你使用 Django 快速开发属于自己的 Blog 网站。</p>
                <h2>教程特点</h2>
                <p>免费、中文、零基础，完整的项目，基于最新版 Django 1.10 和 Python 3.5。</p>
                <p>带你从零开始一步步开发属于自己的博客网站，帮助你以最快的速度掌握 Django 开发的技巧。</p>
                <h2>谁适合这个教程</h2>
                <p><strong>本教程主要面向零基础的 Django 新人。</strong></p>
                <p>只需要一点点 Python 语言的基础，就可以顺利阅读本教程。</p>
                <p>如果你已有一定的 Django 开发经验，也能从本教程中学到更多的 Django 开发技巧。</p>
                <h2>在线预览</h2>
                <p>点击预览：<a href=''>Django Blog Demo</a></p>
                <p><img src='' alt=''/></p>
                <h2>资源列表</h2>
                <p>项目完整代码托管在 GitHub：<a href=''>Django Blog Tutorial</a></p>
                <p>博客前端模板托管在 GitHub：<a href=''>博客模板</a></p>
                <h2>获取帮助</h2>
                <p>在项目开发中遇到问题，即时获取帮助。</p>
                <p>Django 学习小组 QQ 群，扫描下方二维码加入。</p>
                <p><img src='' alt=''/></p>
                <p>或者你也可以将问题的详细描述通过邮件发送至 <a href='mailto:djangostudyteam@163.com' target='_blank'>djangostudyteam@163.com</a>，一般会在
                    24 小时内答复。</p>
            </div>
        </article>
        <section class="comment-area" id="comment-area">
            <hr>
            <h3>发表评论</h3>
            <form action="{% url 'blog:comment' article.id%}" method="post" class="comment-form">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-12">
                        {{form.content}}
                        <button type="submit" class="comment-btn">发表</button>
                    </div>
                </div>    <!-- row -->
            </form>
            <div class="comment-list-panel">
                <h3>评论列表，共 <span>{{article.comment_count}}</span> 条评论</h3>
                <ul class="comment-list list-unstyled">
                    {% getComment article.id as comments %}
                    {% for comment in comments %}
                        <li class="comment-item">
                            <span class="nickname">{{comment.user.nickname}}</span>
                            <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{comment.comment_time}}</time>
                            <div class="text">
                                {{comment.content}}
                            </div>
                        </li>
                    {% empty %}
                        暂无评论
                    {% endfor %}
                </ul>
            </div>
        </section>
    </main>

{% endblock %}