BookLibrary/BookLibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^bookmanage/', include('bookmanage.urls', namespace='bookmanage')),
]

BookLibrary/bookmanage/urls.py
from django.conf.urls import url
from . import views

app_name = 'bookmanage'


urlpatterns = [
    url('^$', views.index, name='index'),
    url('^login/$', views.login, name='login'),
    url('^register/$', views.register, name='register'),
    url('^home/$', views.home, name='home'),
    url('^query/$', views.query, name='query'),
    url('^bookinfo/(\d+)/$', views.book_info, name='bookinfo'),
    url('^info/$', views.info, name='info'),
    url('^borrowing/(\d+)/$', views.borrowing, name='borrowing'),
    url('^history/$', views.history, name='history'),
    url('^modify/$', views.modify, name='modify'),
    url('^active/(.*?)/$', views.active_account, name='active'),
    url('^ajax/$', views.ajax_load, name='ajax'),
]

BookLibrary/bookmanage/models.py
from django.db import models
from tinymce.models import HTMLField
# Create your models here.


class BorrowHistoryManage(models.Manager):
    def crate_borrow_history(self, user, book):
        return self.create(user=user, book=book)


class User(models.Model):
    account = models.CharField(max_length=15, blank=True)
    password = models.CharField(max_length=60, blank=True)
    name = models.CharField(max_length=15, blank=True)
    email = models.EmailField(blank=True)
    college = models.CharField(max_length=15, null=True, blank=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Book(models.Model):
    isbn = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=30)
    author = models.CharField(max_length=15)
    publisher = models.CharField(max_length=30)
    publish_date = models.DateField()
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class BorrowHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    borrow_time = models.DateTimeField(auto_now_add=True)
    return_time = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)
    manage = BorrowHistoryManage()


class Picture(models.Model):
    name = models.CharField(max_length=20)
    path = models.ImageField(upload_to='index')
    index = models.SmallIntegerField(unique=True)


class Message(models.Model):
    title = models.CharField(max_length=30)
    content = HTMLField()

    def __str__(self):
        return self.title

BookLibrary/bookmanage/forms.py
from django.forms import ModelForm
from .models import *


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = '__all__'

BookLibrary/bookmanage/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
# 发送邮件
from django.core.mail import send_mail, send_mass_mail, EmailMultiAlternatives
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from django.conf import settings
from .forms import *
import random
from hashlib import md5


# Create your views here.


def index(request):
    return render(request, 'bookmanage/index.html')


def login(request):
    if request.method == 'GET':
        form = UserForm()
        return render(request, 'bookmanage/reader_login.html', context={'form': form})
    elif request.method == 'POST':
        # 获取表单数据
        form = UserForm(request.POST)
        if form.is_valid():
            print('获取表单数据成功')
            form.save(commit=False)
            account = form.instance.account
            password = form.instance.password
            # 验证用户
            if not check_user(account, password):
                # 验证失败
                return redirect('/bookmanage/login')
            # 用户正确,设置sessionID
            request.session['account'] = request.POST.get('account')
            print('获取表单数据成功')
            return redirect('/bookmanage/home')
        print('登陆失败')
        return redirect('/bookmanage/login')


def register(request):
    if request.method == 'GET':
        form = UserForm()
        return render(request, 'bookmanage/register.html', context={'form': form})
    elif request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            if form.instance.password != request.POST.get('confirm'):
                return redirect('/bookmanage/register')
            if not form.instance.password:
                return redirect('/bookmanage/register')
            # 获取随机账号
            account = make_account()
            form.instance.account = account
            # 加密密码
            form.instance.password = encryption_pwd(form.instance.password)
            form.save()
            email = form.instance.email
            # 发送邮件
            try:
                from django.conf import settings
                # send_mail("用户注册", "<a href=''>注册<a/>", settings.DEFAULT_FROM_EMAIL, ["645933348@qq.com", ])
                # 获取序列化工具
                serutil = Serializer(settings.SECRET_KEY, 50*60)
                # 将字典序列化，并编码
                result = serutil.dumps({"account": account}).decode('utf-8')
                active_url = 'http://127.0.0.1:8000' + reverse('bookmanage:active', args=(result,))
                msg = EmailMultiAlternatives("用户注册", "恭喜您注册成功，您的账号为%s,<a href=%s>点击我进行激活账号</a>"
                                             % (account, active_url), settings.DEFAULT_FROM_EMAIL, [email, ])
                msg.content_subtype = "html"
                # msg.attach_file("./manage.py", "text/*")
                msg.send()
            except Exception as e:
                print(e)

            return redirect('/bookmanage/login')
        else:
            return redirect('/bookmanage/register')


def home(request):
    account = request.session.get('account')
    user = User.objects.all().filter(account=account).first()
    return render(request, 'bookmanage/reader.html', context={'user': user})


def query(request):
    if request.method == 'GET':
        return render(request, 'bookmanage/reader_query.html')
    elif request.method == 'POST':
        item = request.POST.get('item')
        value = request.POST.get('query')

        if item == 'name':
            books = Book.objects.all().filter(name=value)
        elif item == 'author':
            books = Book.objects.all().filter(author=value)
        return render(request, 'bookmanage/reader_query.html', context={'books': books})


def book_info(request, bid):
    book = Book.objects.all().filter(pk=bid).first()
    borrow = BorrowHistory.manage.all().filter(book=book).filter(status=True).first()
    return render(request, 'bookmanage/reader_book.html', context={'book': book, 'borrow': borrow})


def borrowing(request, bid):
    book = Book.objects.all().filter(pk=bid).first()
    if book.status:
        # 以借
        return redirect('/bookmanage/bookinfo/%s' % (bid,))
    book.status = True
    book.save()
    user = User.objects.all().filter(account=request.session.get('account')).first()
    # 创建借阅记录
    BorrowHistory.manage.crate_borrow_history(user=user, book=book)
    return redirect('/bookmanage/bookinfo/%s' % (bid,))


def info(request):
    account = request.session.get('account')
    user = User.objects.all().filter(account=account).first()
    return render(request, 'bookmanage/reader_info.html', context={'user': user})


def history(request):
    user = User.objects.all().filter(account=request.session.get('account')).first()
    borrows = BorrowHistory.manage.all().filter(user=user)
    return render(request, 'bookmanage/reader_history.html', context={'borrows': borrows})


def modify(request):
    if request.method == 'GET':
        return render(request, 'bookmanage/reader_modify.html')
    elif request.method == 'POST':

        account = request.session.get('account')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        if password != confirm_password:
            # 两次密码不一致
            return redirect('/bookmanage/modify')
        # 获取原密码
        old_password = request.POST.get('old_password')
        user = check_user(account, old_password)
        if not user:
            # 密码错误
            return redirect('/bookmanage/modify')
        # 验证成功,修改信息
        user.name = request.POST.get('name')
        user.password = encryption_pwd(request.POST.get('password'))
        user.email = request.POST.get('email')
        user.college = request.POST.get('college')
        user.save()
        return redirect('/bookmanage/home')


def make_account():
    account = ''
    for i in range(0, 9):
        account += str(random.randint(0, 9))
    if User.objects.all().filter(account=account).first():
        return make_account()
    return account


def encryption_pwd(password, encode='utf-8'):
    m = md5()
    password = str(password)
    m.update(password.encode(encode))
    return m.hexdigest()


def check_user(account, password):
    user = User.objects.all().filter(account=account).first()
    if not user:
        return False
    if user.password != encryption_pwd(str(password)):
        return False
    return user


def active_account(request, account):
    """
    激活账号
    :param request:
    :return:
    """
    # 获取反序列化工具
    dserutil = Serializer(settings.SECRET_KEY, 50)
    try:
        obj = dserutil.loads(account)
        account = obj['account']
        user = User.objects.all().filter(account=account).first()
        user.status = True
        user.save()
        return HttpResponse('恭喜您激活成功')
    except Exception:
        return HttpResponse('激活链接已过期')


def ajax_load(request):
    print('请求成功')
    return HttpResponse('请求成功')

BookLibrary/templates/bookmanage/index.html
{% extends "bookmanage/layout.html" %}
{% load extend_tag %}
{% block title %}主页{% endblock %}
{% block staticlink %}
    <link rel=stylesheet type=text/css href="/static/bookmanage/css/style.css">
    <link rel="stylesheet" href="/static/bookmanage/js/lib/bootstrap-3.3.7-dist/css/bootstrap.css">
    <script src="/static/bookmanage/js/lib/jquery-2.1.4/jquery-2.1.4.js"></script>
    <script src="/static/bookmanage/js/lib/bootstrap-3.3.7-dist/js/bootstrap.js"></script>
{% endblock %}

{% block link %}
  <h4><a href="{% url 'bookmanage:login' %}">读者登录 </a></h4>
{% endblock %}

{% block body %}
  <h2>欢迎使用</h2>

<div class="col-md-12">
    {% get_pictures as pictures %}
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            {% for picture in pictures %}
                {% if picture.id == 1 %}
                <li data-target="#carousel-example-generic" data-slide-to="{{picture.id}}" class="active"></li>
                {% else %}
                    <li data-target="#carousel-example-generic" data-slide-to="{{picture.id}}"></li>
                {% endif %}
            {% endfor %}
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">

            {% for picture in pictures %}
                {% if picture.id == 1 %}
                    <div class="item active">
                        <img src="/static/media/{{ picture.path}}" alt="图片加载失败">
                        <div class="carousel-caption">
                        </div>
                    </div>
                {% else %}
                    <div class="item">
                        <img src="/static/media/{{ picture.path}}" alt="图片加载失败">
                        <div class="carousel-caption">

                        </div>
                    </div>
                {% endif %}

            {% empty %}

            {% endfor %}

        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>

        <script>
            $('.carousel').carousel({
                interval: 2000
            })
        </script>
    </div>

</div>
<div class="articles">
    {% get_articles as articles %}
    {% for article in articles %}
        <div class="article" >
            <div class="title">
            {{article.title}}
            </div>
            <div class="content">
                {{article.content|safe}}
            </div>
        </div>
    {% empty %}

    {% endfor %}
    {% csrf_token %}
    <button class="get">GET请求</button>
    <button class="post">POST请求</button>
    <div class="ajax"></div>
    <script>
        $('.get').click(function () {
            $.ajax({
                url: '/bookmanage/ajax/',
                type: 'get',
                success:function (data) {
                   $(".ajax").text(data);
                }
            })
        })
    </script>

    <script>
        $('.post').click(function () {
            $.ajax({
                url: '/bookmanage/ajax/',
                type: 'post',
                data: {
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                },
                success:function (data) {
                   $(".ajax").text(data);
                }
            })
        })
    </script>



</div>


{% endblock %}

BookLibrary/templates/bookmanage/layout.html
<!doctype html>
<title> {% block title %} 图书管理系统 {% endblock %} </title>
{% block staticlink %}
    <link rel=stylesheet type=text/css href="/static/bookmanage/css/style.css">
{% endblock %}
<div class=page>
  <h1>图书管理系统</h1>
  <div class=navigation>
    {% block link %}{% endblock %}
  </div>
  <div class=body>
    {% block body %}{% endblock %}
   </div>
  <div class=footer>
     <p>&mdash; 华中科技大学</p>
  </div>
</div>
    

BookLibrary/templates/bookmanage/manager.html
{% extends 'layout.html' %}
{% block title%} 功能导航 {% endblock %}
{% block link%} 
	<a href="{{ url_for('logout')}}"> 注销 [{{ g.user}}]</a> | 
	<a href="{{ url_for('manager_books') }}"> 图书管理 </a> |
	<a href="{{ url_for('manager_users') }}"> 用户管理 </a> 
{%  endblock%}

BookLibrary/templates/bookmanage/manager_books_add.html
{% extends "layout.html" %}
{% block title %} 增添书目 {% endblock %}
{% block link %} 
	<a href="{{ url_for('manager_books')}}"> 返回 </a>
{% endblock %}
{% block body %}
	<h2> 增添书目 </h2>
	{% if error %}
	<div class = error>
	  <strong>Error : </strong> {{error}}
	</div>
	{% endif %}
	<form action="" method=post>
	  <dl>
	    <dt>ISBN: </dt>
	    <dd><input type=text name=id size=30> </dd>
	    <dt>书名:</dt>
	    <dd><input type=text name=name size=30> </dd>
	    <dt>作者:</dt>
	    <dd><input type=text name=author size=30> </dd>
	    <dt>出版社:</dt>
	    <dd><input type=text name=company size=30> </dd>
	    <dt>出版日期:</dt>
	    <dd><input type=text name=date size=30> </dd>
	  </dl>
	  <div class=actions>
	    <input type=submit value="添加">
	  </div>
	</form>

{% endblock %} 

BookLibrary/templates/bookmanage/manager_modify.html
{% extends "layout.html" %}
{% block title %} 修改书目信息 {% endblock %}
{% block link %} 
	{% if book %}
	<a href="{{ url_for('manager_book', id=book.book_id)}}"> 返回 </a>
	{% endif %}
{% endblock %}
{% block body %}
	<h2> 修改书目信息 </h2>
	{% if error %}
	<div class = error>
	  <strong>Error : </strong> {{error}}
	</div>
	{% endif %}
	{% if book %}
	<form action="" method=post>
	  <dl>
	    <dt>书名:</dt>
	    <dd><input type=text name=name size=30 value={{book.book_name}}> </dd>
	    <dt>作者:</dt>
	    <dd><input type=text name=author size=30 value={{book.author}}> </dd>
	    <dt>出版社:</dt>
	    <dd><input type=text name=company size=30 value={{book.publish_com}}> </dd>
	    <dt>出版日期:</dt>
	    <dd><input type=text name=date size=30 value={{book.publish_date}}> </dd>
	  </dl>
	  <div class=actions>
	    <input type=submit value="修改">
	  </div>
	</form>
	{% endif %}
{% endblock %} 

BookLibrary/templates/bookmanage/manager_userinfo.html
{% extends "bookmanage/layout.html" %}
{% block title %} 用户主页 {% endblock %}

{% block link %}
	<a href="{{ url_for('manager_users') }}"> 返回  </a>  |
	<a href="{{ url_for('manger_user_modify', id=user.user_id)}}"> 修改 </a> | 
	<a href="{{ url_for('manger_user_delete', id=user.user_id)}}"> 注销 </a>
{% endblock %}
{% block body  %}
	<h2> 用户信息 </h2>
	{% if user %}
	<li> 用户名 {{user.user_name}} </li>
	<li> 学院名 {{user.college}} </li>
	<li> 学号 {{user.num}} </li>
	<li> 邮箱 {{user.email}} </li>
	{% endif %}

{% endblock %}

BookLibrary/templates/bookmanage/manager_users.html
{% extends 'layout.html' %}
{% block title%} 用户管理 {% endblock %}
{% block link%} 
	<a href="{{ url_for('manager')}}"> 返回 </a> 
{%  endblock%}
{% block body%}
	<h2> 用户管理 </h2>
	<table width="600" border="1", align="center">
	  <tr>
	    <th align="center"> 用户名 </th>
	    <th align="center"> 用户信息 </th>
	  </tr>
	  {% for user in users%}
	  <tr>
	    <th align="center"> {{user.user_name}}</th>
	    <th align="center"> <a href="{{ url_for('manager_user', id=user.user_id)}}"> 点击进入 </a> </th>
	  </tr>
	  {% endfor %}
	</table>
{% endblock%}

BookLibrary/templates/bookmanage/reader.html
{% extends 'bookmanage/layout.html' %}
{% block title %} 欢迎使用 {% endblock %}
{% block link %} 
	<a href="{% url 'bookmanage:index' %}"> 注销[{{user.name}}] </a> |
	<a href="{% url 'bookmanage:query' %}"> 查询 </a> |
	<a href="{% url 'bookmanage:info' %}"> 查看个人信息 </a> |
	<a href="{% url 'bookmanage:history' %}"> 查看阅读记录 </a>

{% endblock %}

{% block body %}
	<h2> 欢迎使用 </h2>
{% endblock %}

BookLibrary/templates/bookmanage/reader_book.html
{% extends 'bookmanage/layout.html' %}

{% block title %} 书目信息 {% endblock %}
{% block link %} 
	{% if book %}
	<a href="{% url 'bookmanage:query' %}"> 返回 </a>
	{% endif %}
{% endblock %}

{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}
	<h2> 书目信息 </h2>
	{% if book %}
	<li> ISBN {{book.isbn}} </li>
	<li> 书名  {{book.name}} </li>
	<li> 作者  {{book.author}} </li>
	<li> 出版社 {{book.publisher}} </li>
	<li> 出版日期 {{book.publish_date}} </li>
	{% endif %}
	<div >
	  <h2 > 借阅信息 </h2>
	  {% if borrow  %}
	  <li> 借阅者姓名 {{borrow.user.name}}</li>
	  <li> 借阅日期  {{borrow.borrow_time}}</li>
	  <li> 还书日期  {{borrow.return_time}}</li>
	  {% else %}
	  <li> 无 </li>
	  {% endif %}
	  <form action="{% url 'bookmanage:borrowing'  book.id%}" method=post>
		{% csrf_token %}
	    <div class=actions>
	      <input type=submit value="借阅">
	    </div>
	  </form>
{% endblock %}

BookLibrary/templates/bookmanage/reader_history.html
{% extends "bookmanage/layout.html" %}
{% block title %} 阅读记录 {% endblock %}
{% block link %} 
	<a href="{% url 'bookmanage:home' %}"> 返回 </a>
{% endblock %}
{% block body %}
	<table width="600" border="1" align="center">
	  <tr>
	    <th align="center"> 书名 </th>
	    <th align="center"> 借书日期 </th>	
	    <th align="center"> 还书日期 </th>
	    <th align="center"> 状态 </th>
	  </tr>
	  {% for borrow in borrows %}
	  <tr>
	    <th align="center"> {{borrow.book.name}} </th>
	    <th align="center"> {{borrow.borrow_time}}</th>
	    <th align="center"> {{borrow.return_time}} </th>
	    <th align="center"> {{borrow.status}} </th>
	  </tr>
	  {% endfor %}
	</table>	

{% endblock %}

BookLibrary/templates/bookmanage/reader_info.html
{% extends "bookmanage/layout.html" %}
{% block title %} 个人主页 {% endblock %}

{% block link %}
	<a href="{% url 'bookmanage:home' %}"> 返回  </a>  |
	<a href="{% url 'bookmanage:modify' %}"> 修改 </a>
{% endblock %}
{% block body  %}
	<h2> 用户信息 </h2>
	{% if user %}
	<li> 用户名 {{user.name}} </li>
	<li> 学院名 {{user.college}} </li>
	<li> 学号 {{user.account}} </li>
	<li> 邮箱 {{user.email}} </li>
	{% endif %}

{% endblock %}

BookLibrary/templates/bookmanage/reader_modify.html
{% extends "bookmanage/layout.html" %}
{% block title %} 个人信息修改 {% endblock %}
{% block link %} 
	<a href="{% url 'bookmanage:home' %}"> 返回 </a>
{% endblock %}
{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
	<form action="{% url 'bookmanage:modify' %}" method=post>
		{% csrf_token %}
		<p>用户名&nbsp;&nbsp;&nbsp;:<input type="text" name="name"></p>
		<p>旧密码&nbsp;&nbsp;&nbsp;:<input type="password" name="old_password"></p>
		<p>新密码&nbsp;&nbsp;&nbsp;:<input type="password" name="password"></p>
		<p>确认密码:<input type="password" name="confirm_password"></p>
		<p>学院:<input type="text" name="college"></p>
		<p>邮箱:<input type="email" name="email"></p>
	  <div class=actions><input type=submit value="确定"></div>
	</form>

{% endblock %}

BookLibrary/templates/bookmanage/reader_query.html
{% extends "bookmanage/layout.html" %}
{% block title%} 查询  {% endblock %}
{% block link %} 
	<a href="{% url 'bookmanage:home' %}"> 返回 </a>
{% endblock %}
{% block body %}
	<h2> 查询 </h2> 
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}

    <div class=actions>
	  <form action="{% url 'bookmanage:query' %}" method="post">
		{% csrf_token %}
	    <dd>
			<select name="item">
				<option value="name"  > 书名 </option>
				<option value="author"> 作者 </option>
			</select>
			<input type="text" name="query" size="80">
			<input type="submit" value="查询">
	    </dd> 
	  </form>
	</div>

	{% if books %}

	<table width="600" border="1" align="center">
		  <tr>
			<th align="center"> ISBN </th>
			<th align="center"> 书名 </th>
			<th align="center"> 作者</th>
			<th align="center"> 出版商 </th>
			<th align="center"> 出版时间 </th>
			<th align="center"> 查看信息 </th>
		  </tr>
	  {% for book in books %}
	  <tr>
	    <th align="center"> {{book.isbn}}</th>
	    <th align="center"> {{book.name}} </th>
	    <th align="center"> {{book.author}}</th>
	    <th align="center"> {{book.publisher}} </th>
	    <th align="center"> {{book.publish_date}}</th>
	    <th align="center"> <a href="{% url 'bookmanage:bookinfo'  book.id %}"> 点击进入 </a> </th>
	  </tr>
	  {% endfor %}
	</table>
	{% endif %}
{% endblock %}

BookLibrary/templates/bookmanage/register.html
{% extends "bookmanage/layout.html" %}
{% block title %} 注册 {% endblock %}
{% block link %} 
	<a href="{% url 'bookmanage:login' %}"> 返回 </a>
{% endblock %}
{% block body %}
	{% if error %}
	<div class=error>
	  <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}
	<form action="{% url 'bookmanage:register' %}" method=post>
		{% csrf_token %}
		<p>用户名&nbsp;&nbsp;&nbsp;: {{form.name}}</p>
		<p>密&nbsp;&nbsp;&nbsp;码&nbsp;&nbsp;&nbsp;: {{form.password}}</p>
		<p>确认密码: <input type="password" name="confirm"></p>
		<p>学&nbsp;&nbsp;&nbsp;院&nbsp;&nbsp;&nbsp;: {{form.college}}</p>
		<p>邮&nbsp;&nbsp;&nbsp;箱&nbsp;&nbsp;&nbsp;: {{form.email}}</p>
	  <div class=actions><input type=submit value="注册"></div>
	</form>

{% endblock %}