blogProject/blog/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views

app_name = "blog"

urlpatterns = [
    # 注册主页地址
    url(r'^$', views.index, name="index"),
    url(r'login_register$', views.login_register, name="login_register"),
    url(r'login$', views.login, name="login"),
    url(r'register$', views.register, name="register"),
    url(r'home$', views.home, name="home"),
    url(r'publish$', views.publish_article, name="publish"),
    url(r'manage_article$', views.manage_article, name="manage_article"),
    url(r'update_article$', views.update_article, name="update_article"),
    # url(r'detail/(%d+)$', views.look_article, name="detail"),
    url(r'detail/.*', views.detail_article, name="detail"),
    url(r'delete/.*', views.del_article, name="delete"),
    url(r'comment/.*', views.comment_article, name="comment"),
    url(r'^verify/$', views.verify, name='verify')
]

blogProject/blogProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url


# 为新建的项目下的url注册
# url(r'^', include('blog.urls', namespace='blog'))

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace="blog")),
]

blogProject/blog/models.py
from django.db import models
from tinymce.models import HTMLField
# Create your models here.


class User(models.Model):
    """
        创建用户表，继承model下的Model类，该类提供了与数据库交互的所有方法
    """

    # 构建字段,用户账号
    account = models.CharField(max_length=20, unique=True)
    # 用户密码
    password = models.CharField(max_length=30)
    # 用户昵称
    nickname = models.CharField(max_length=20, blank=True, default="新用户")
    # 用户邮箱
    email = models.CharField(max_length=30, blank=True, default="待完善")
    # 用户积分
    integral = models.IntegerField(default=10)
    # 用户说明
    describe = models.CharField(max_length=255, blank=True, default="暂无说明")
    # 注册时间
    register_time = models.DateTimeField(auto_now_add=True)
    # 是否激活
    is_delete = models.BooleanField(default=False)

    def __str__(self):
        return self.account

    def show_account(self):
        return self.account
    show_account.short_description = "账号"

    def show_nickname(self):
        return self.nickname
    show_nickname.short_description = "昵称"

    def show_email(self):
        return self.email
    show_email.short_description = "邮箱"

    def show_integral(self):
        return self.integral
    show_integral.short_description = "积分"

    def show_register_time(self):
        return self.register_time
    show_register_time.short_description = "注册时间"


class Article(models.Model):
    """
        构建文章对象
    """
    # 标题
    title = models.CharField(max_length=30)
    # 内容
    content = HTMLField()
    # 所属用户
    user = models.ForeignKey("User", on_delete=models.CASCADE)
    # 阅读次数
    read_count = models.IntegerField(default=0)
    # 评论数
    comment_count = models.IntegerField(default=0)
    # 发布时间
    publish_time = models.DateTimeField(auto_now_add=True)

    def show_title(self):
        return self.title
    show_title.short_description = "标题"

    def show_read_count(self):
        return self.read_count
    show_read_count.short_description = "浏览次数"

    def show_publish_time(self):
        return self.publish_time
    show_publish_time.short_description = "发布时间"

    def __str__(self):
        return self.title


class Comment(models.Model):
    """定义评论类"""
    # 评论人
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # 评论文章
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # 评论内容
    content = models.CharField(max_length=255)
    # 评论时间
    comment_time = models.DateTimeField(auto_now_add=True)

    def show_user(self):
        return self.user

    def show_article(self):
        return self.article

    def show_comment_time(self):
        return self.comment_time

    show_user.short_description = "评论人"
    show_article.short_description = "文章标题"
    show_comment_time.short_description = "发布时间"

blogProject/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
# 邮件类库
from django.core.mail import send_mail, send_mass_mail
from PIL import Image, ImageDraw, ImageFont
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from django.conf import settings
import random,io
from .models import *

# Create your views here.


def serialize(request):
    # 获取序列化工具
    serutil = Serializer(settings.SECRET_KEY, 50)
    # 将字典序列化，并编码
    result = serutil.dumps({"name": '值'}).decode('utf-8')

    # 获取反序列化工具
    dserutil = Serializer(settings.SECRET_KEY, 50)
    try:
        obj = dserutil.loads(result)
        name = obj['name']
    except Exception:
        pass




def index(request):
    """
    主页处理函数
    :param request:请求对象
    :return: 主页html模板
    """
    return render(request, 'blog/index.html')


def login_register(request):
    """
    登录注册页面
    :param request:
    :return:
    """

    return render(request, 'blog/login.html')


def login(request):
    """
    用户登录界面
    :param request:
    :return:
    """
    if request.method == "GET":
        return render(request, 'blog/login.html')

    elif request.method == "POST":
        account = request.POST["account"]
        pwd = request.POST["password"]
        verify_code = request.POST["verifycode"]
        users = User.objects.all().filter(account=account)
        if verify_code != request.session["verifycode"]:
            # 验证码错误
            return HttpResponseRedirect('/blog/login')

        if not users.exists():
            # 用户不存在
            return HttpResponseRedirect('/blog/login')

        if users.first().password != pwd:
            # 密码错误
            request.session['account'] = request.POST["account"]
            return HttpResponseRedirect('/blog/login')

        # 验证成功
        return HttpResponseRedirect('/blog/home')


def register(request):
    """
    注册处理函数
    :param request:
    :return:
    """

    if request.method == "GET":
        return render(request, 'blog/login.html')

    elif request.method == "POST":
        account = request.POST["account"]
        pwd = request.POST["password"]
        verify_code = request.POST["verifycode"]
        if verify_code != request.session["verifycode"]:
            # 验证码错误
            return HttpResponseRedirect('/blog/login')

        if User.objects.all().filter(account=account):
            return HttpResponseRedirect('/blog/register')
        else:
            u = User()
            u.account = account
            u.password = pwd
            u.save()
            return render(request, 'blog/index.html')


def home(request):
    """
    用户主页处理函数
    :param request: 请求对象
    :return: 注册页面html
    """
    account = request.session.get('account')
    articles = Article.objects.all()
    return render(request, 'blog/home.html', context={"articles": articles, "account": account})


def show_publish_article(request):
    """
    发表文章处理函数
    :param request:请求的对象
    :return:返回写博客页面
    """
    return render(request, "blog/publish.html")


def publish_article(request):
    """
    发表文章处理函数
    :param request:请求的对象
    :return:返回写博客页面
    """
    if request.method == "GET":
        return render(request, "blog/publish.html")
    elif request.method == "POST":
        account = request.session.get('account')
        user = User.objects.all().filter(account=account).first()
        title = request.POST["title"]
        content = request.POST["content"]
        article = Article()
        article.title = title
        article.content = content
        article.user = user
        article.save()
        return HttpResponseRedirect("/blog/home")


def manage_article(request):
    """
    管理文章处理函数
    :param request:请求的用户
    :return: html网页
    """
    account = request.session.get('account')
    articles = User.objects.all().filter(account=account).first().article_set.all
    return render(request, "blog/manage_article.html", context={"articles": articles})


def detail_article(request):
    """
    查看文章
    :param request:
    :return:
    """
    aid = request.GET["aid"]
    articles = Article.objects.all().filter(pk=aid)
    if articles.exists():
        article = articles.first()
        article.read_count += 1
        article.save()
        return render(request, "blog/detail.html", context={"article": article})
    else:
        return HttpResponseRedirect("/blog/home")


def update_article(request):
    """
    修改文章
    :param request:修改文章处理函数
    :return: 修改后得html
    """
    return


def del_article(request):
    """
    处理删除文章请求
    :param request:
    :return:
    """
    account = request.session.get("account")
    aid = request.GET["aid"]
    Article.objects.all().filter(pk=aid).delete()
    articles = User.objects.all().filter(account=account).first().article_set.all
    return render(request, "blog/manage_article.html", context={"articles": articles})


def comment_article(request):
    """
    评论文章处理
    :param request:
    :return:
    """
    account = request.session.get("account")
    aid = request.GET["aid"]
    c = Comment()
    c.user = User.objects.all().filter(account=account).first()
    article = Article.objects.all().filter(pk=aid).first()
    c.article = article
    c.content = request.GET['comment']
    c.save()
    article.comment_count += 1
    article.save()
    # return HttpResponseRedirect("/blog/detail/?")
    return render(request, "blog/detail.html", context={"article": article})


def send_email(request):
    """
    发送邮件
    :param request:
    :return:
    """
    return render(request, 'blog/send_email.html')


def verify(request):
    """
    验证码
    :param request:
    :return:
    """
    # 定义背景图片的背景颜色、宽、高
    bg_color = (random.randrange(20, 100),
               random.randrange(20, 100),
               random.randrange(20, 100))
    width = 200
    height = 50
    # 创建画面对象
    im = Image.new('RGB', (width, height), bg_color)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 制造噪点
    for i in range(100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy=xy, fill=fill)

    # 定义验证码的被选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    rand_str = ''
    # 随机取出四个字母或数字
    for i in range(4):
        rand_str += str1[random.randrange(0, len(str1))]
    # 构造字体对象
    font = ImageFont.truetype('arial.ttf', 23)
    # 字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制四个字
    draw.text((10, 12), rand_str[0], font=font, fill=fontcolor)
    draw.text((50, 12), rand_str[1], font=font, fill=fontcolor)
    draw.text((100, 12), rand_str[2], font=font, fill=fontcolor)
    draw.text((150, 12), rand_str[3], font=font, fill=fontcolor)
    # 释放画笔
    del draw
    # 返回session
    request.session['verifycode'] = rand_str
    # 获取io流
    f = io.BytesIO()
    # 将图片保存
    im.save(f, 'png')
    # 将图片的值发给前端页面进行渲染
    return HttpResponse(f.getvalue(), 'image/png')

blogProject/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页面</title>



    <link rel="stylesheet" href="/static/blog/js/lib/bootstrap-3.3.7-dist/css/bootstrap.css">
    <script src="/static/blog/js/lib/jquery-2.1.4/jquery-2.1.4.js"></script>
    <script src="/static/blog/js/lib/bootstrap-3.3.7-dist/js/bootstrap.js"></script>


</head>
<body>
    <nav class="navbar navbar-default">
			<div class="container">
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active">
							<a href="{% url 'blog:home' %}"><span class="glyphicon glyphicon-home"></span>首页<span class="sr-only">(current)</span></a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-tag"></span> 博客</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-book"></span> 学院</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> 商城</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-star"></span> VIP会员</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-download-alt"></span> 下载</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-th-large"></span> APP</a>
						</li>
					</ul>

					<form class="navbar-form navbar-left">
						<div class="input-group">
							<input type="text" class="form-control" placeholder="搜索博客">
							<span class="input-group-btn">
                            <button class="btn btn-default" type="button">搜索</button>
                        </span>
						</div>
					</form>

					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="/publish"> <span class="glyphicon glyphicon-pencil"></span>写博客</a>
						</li>
						<li>
							<a href="#"> <span class="glyphicon glyphicon-envelope"></span>消息</a>
						</li>
						<li>
							<div class="dropdown">
						  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="background-color: #f7f7f7;border: none;margin-top: 8px;color: #777">
							管理
							<span class="caret"></span>
						  </button>
						  <ul class="dropdown-menu" aria-labelledby="dropdownMenu3">
							<li><a href="#">我的关注</a></li>
							<li><a href="#">我的收藏</a></li>
							<li><a href="#">个人中心</a></li>
							<li><a href="#">账号设置</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="#">我的博客</a></li>
							<li><a href="{% url 'blog:manage_article' %}">管理博客</a></li>
							<li><a href="#">我的学院</a></li>
							<li><a href="#">我的下载</a></li>
							  <li role="separator" class="divider"></li>
							  <li><a href="#">我的C币</a></li>
							  <li><a href="#">订单中心</a></li>
							  <li role="separator" class="divider"></li>
							  <li><a href="#">帮助</a></li>
							  <li><a href="/">退出</a></li>

						  </ul>
						</div>
						</li>
					</ul>


				</div>

			</div>
		</nav>

    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8" style="border-bottom: 1px solid #777777">
                <div style="border-bottom: 1px solid #777777; margin-bottom: 15px;"><h2>{{article.title}}</h2></div>
				<div>{{article.content|safe}}</div>
				{% for comment in article.comment_set.all %}
					<div style="margin-top: 20px; margin-bottom: 20px">
						<p><a href="">{{comment.user.nickname}}:</a> <span style="float: right">{{comment.comment_time}}</span></p>
						<p>{{comment.content}}</p>
            	</div>

				{%  endfor %}
            </div>
			<div class="col-md-8 col-md-offset-2" style="margin-top: 15px">
				<form action="{% url 'blog:comment' %}" method="get">
					<input type="hidden" name="aid" value={{article.id}} />
					<textarea class="form-control" rows="3" name="comment"></textarea>
					<button type="submit" class="btn btn-default" style="margin-top: 5px">评论</button>
				</form>
				
			</div>

        </div>
    </div>

</body>
</html>

blogProject/templates/blog/home.html
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="UTF-8">
		<title>用户主页</title>

		<link rel="stylesheet" href="/static/blog/js/lib/bootstrap-3.3.7-dist/css/bootstrap.css">
		<script src="/static/blog/js/lib/jquery-2.1.4/jquery-2.1.4.js"></script>
		<script src="/static/blog/js/lib/bootstrap-3.3.7-dist/js/bootstrap.js"></script>

		<!--<link rel="stylesheet" href="../static/css/login.css">-->
	</head>

	<body>

		<nav class="navbar navbar-default">
			<div class="container">
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active">
							<a href="#"><span class="glyphicon glyphicon-home"></span>首页<span class="sr-only">(current)</span></a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-tag"></span> 博客</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-book"></span> 学院</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> 商城</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-star"></span> VIP会员</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-download-alt"></span> 下载</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-th-large"></span> APP</a>
						</li>
					</ul>

					<form class="navbar-form navbar-left">
						<div class="input-group">
							<input type="text" class="form-control" placeholder="搜索博客">
							<span class="input-group-btn">
                            <button class="btn btn-default" type="button">搜索</button>
                        </span>
						</div>
					</form>

					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="{% url 'blog:publish' %}"> <span class="glyphicon glyphicon-pencil"></span>写博客</a>
						</li>
						<li>
							<a href="#"> <span class="glyphicon glyphicon-envelope"></span>消息</a>
						</li>
						<li>
							<div class="dropdown">
						  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="background-color: #f7f7f7;border: none;margin-top: 8px;color: #777">
							管理
							<span class="caret"></span>
						  </button>
						  <ul class="dropdown-menu" aria-labelledby="dropdownMenu3">
							<li><a href="#">我的关注</a></li>
							<li><a href="#">我的收藏</a></li>
							<li><a href="#">个人中心</a></li>
							<li><a href="#">账号设置</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="#">我的博客</a></li>
							<li><a href="{% url 'blog:manage_article' %}">管理博客</a></li>
							<li><a href="#">我的学院</a></li>
							<li><a href="#">我的下载</a></li>
							  <li role="separator" class="divider"></li>
							  <li><a href="#">我的C币</a></li>
							  <li><a href="#">订单中心</a></li>
							  <li role="separator" class="divider"></li>
							  <li><a href="#">帮助</a></li>
							  <li><a href="{% url 'blog:index' %}">退出</a></li>

						  </ul>
						</div>
						</li>
					</ul>


				</div>

			</div>
		</nav>

		<div class="container">
			<div class="row">
				<div class="col-md-2">
					<div class="list-group">
						<button type="button" class="list-group-item">推荐</button>
						<button type="button" class="list-group-item">关注</button>
						<button type="button" class="list-group-item">程序人生</button>
						<button type="button" class="list-group-item">前端</button>
						<button type="button" class="list-group-item">架构</button>
						<button type="button" class="list-group-item">区块链</button>
						<button type="button" class="list-group-item">编程语言</button>
						<button type="button" class="list-group-item">数据库</button>
						<button type="button" class="list-group-item">游戏开发</button>
						<button type="button" class="list-group-item">移动开发</button>
						<button type="button" class="list-group-item">运维</button>
						<button type="button" class="list-group-item">人工智能</button>
						<button type="button" class="list-group-item">安全</button>
						<button type="button" class="list-group-item">云计算/大数据</button>
						<button type="button" class="list-group-item">研发管理类</button>
						<button type="button" class="list-group-item">物联网</button>
						<button type="button" class="list-group-item">计算机基础</button>
						<button type="button" class="list-group-item">其他</button>
					</div>
				</div>
				<div class="col-md-7">
					<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
						<!-- Indicators -->
						<ol class="carousel-indicators">
							<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
							<li data-target="#carousel-example-generic" data-slide-to="1"></li>
							<li data-target="#carousel-example-generic" data-slide-to="2"></li>
						</ol>

						<!-- Wrapper for slides -->
						<div class="carousel-inner" role="listbox">
							<div class="item active">
								<img src="/static/blog/images/user_home/lb.jpg" alt="...">
								<div class="carousel-caption">

								</div>
							</div>
							<div class="item">
								<img src="/static/blog/images/user_home/lb.jpg" alt="...">
								<div class="carousel-caption">

								</div>
							</div>
							<div class="item">
								<img src="/static/blog/images/user_home/lb.jpg" alt="...">
								<div class="carousel-caption">

								</div>
							</div>

						</div>

						<!-- Controls -->
						<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
							<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
							<span class="sr-only">Previous</span>
						</a>
						<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
							<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
							<span class="sr-only">Next</span>
						</a>

						<script>
							$('.carousel').carousel({
								interval: 2000
							})
						</script>
					</div>

					{% for article in articles %}

						<div class="panel panel-default">
							<div class="panel-heading">
								<a href="{% url 'blog:detail' %}?aid={{article.id}}"><h3>{{article.title}}</h3></a></div>
							<div class="panel-body">
								<p>{{article.content|safe}}</p>
								<div>
									<div class="left" style="float: left">
										<img src="/static/blog/images/user_home/ss.jpeg" alt="头像" class="img-circle" style="width:32px;">
										<a href="#">{{article.user.nickname}}</a>
										<a href="#"></a>
										<span>{{article.publish_time}}</span>
									</div>
									<div class="right" style="float: right">
										<a href="#">阅览数：{{article.read_count}}</a>

										<a href="#">评论数:{{article.comment_count}}</a>
									</div>
								</div>
							</div>
						</div>
					{% empty %}
						<span></span>
					{% endfor %}
				</div>
				<div class="col-md-3">
					<div class="list-group">
						<a href="#" class="list-group-item list-group-item-success">今日推荐</a>
						<div>
							<a href="#">今日推荐内容</a><br>
							<a href="#">大热点</a>
						</div>
						<a href="#" class="list-group-item list-group-item-info">热门搜索</a>
						<div>
							<a href="#">热门搜索内容</a><br>
							<a href="#">python又火了</a>
						</div>
						<a href="#" class="list-group-item list-group-item-warning">大家都在看</a>
						<div>
							<a href="#">python学习指南</a>
							<br>
							<a href="#">java大师之路</a>
						</div>
						<a href="#" class="list-group-item list-group-item-danger">作者推荐</a>
						<div class="media">
							<div class="media-left media-middle">
								<a href="#">
									<img class="media-object img-circle" src="/static/blog/images/head/ss.jpeg" alt="头像" style="width: 64px;">
								</a>
							</div>
							<div class="media-body">
								<h4 class="media-heading">simple</h4> 老男孩系统讲解Web集群所涉及的各种技术，针对整个集群中的每个网络服务节点给出解决方案，
							</div>
						</div>

						<div class="media">
							<div class="media-left media-middle">
								<a href="#">
									<img class="media-object img-circle" src="/static/blog/images/head/mm.jpeg" alt="头像" style="width: 64px;">
								</a>
							</div>
							<div class="media-body">
								<h4 class="media-heading">tom</h4> Java 工程师掌握 Spring Boot 技术栈，实践微服务，针对整个集群中的每个网络服务节点给出解决方案，
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>

	</body>

</html>

blogProject/templates/blog/manage_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>管理文章</title>

    <link rel="stylesheet" href="/static/blog/js/lib/bootstrap-3.3.7-dist/css/bootstrap.css">
    <script src="/static/blog/js/lib/jquery-2.1.4/jquery-2.1.4.js"></script>
    <script src="/static/blog/js/lib/bootstrap-3.3.7-dist/js/bootstrap.js"></script>

</head>
<body style="background-color: cadetblue">

    <nav class="navbar navbar-default">
			<div class="container">
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active">
							<a href="{% url 'blog:home' %}"><span class="glyphicon glyphicon-home"></span>首页<span class="sr-only">(current)</span></a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-tag"></span> 博客</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-book"></span> 学院</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-shopping-cart"></span> 商城</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-star"></span> VIP会员</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-download-alt"></span> 下载</a>
						</li>
						<li>
							<a href="#"><span class="glyphicon glyphicon-th-large"></span> APP</a>
						</li>
					</ul>

					<form class="navbar-form navbar-left">
						<div class="input-group">
							<input type="text" class="form-control" placeholder="搜索博客">
							<span class="input-group-btn">
                            <button class="btn btn-default" type="button">搜索</button>
                        </span>
						</div>
					</form>

					<ul class="nav navbar-nav navbar-right">
						<li>
							<a href="/publish"> <span class="glyphicon glyphicon-pencil"></span>写博客</a>
						</li>
						<li>
							<a href="#"> <span class="glyphicon glyphicon-envelope"></span>消息</a>
						</li>
						<li>
							<a href="#"> <span class="glyphicon glyphicon-cog"></span>设置</a>
						</li>
					</ul>
				</div>

			</div>
		</nav>


    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="list-group">
                  <a href="#" class="list-group-item list-group-item-success">查看主页</a>
                  <a href="#" class="list-group-item list-group-item-info">文章管理</a>
                  <a href="#" class="list-group-item list-group-item-warning">评论管理</a>
                  <a href="#" class="list-group-item list-group-item-danger">个人分类管理</a>
                </div>
            </div>

            <div class="col-md-9">

				{% for article in articles %}
					<div class="panel panel-default">
						<div class="panel-heading">
							<h3>{{article.title}}</h3></div>
						<div class="panel-body">
							<p>{{article.content}}</p>
							<div>
								<div class="left" style="float: left">
									<span>{{article.publish_time}}</span>
									<a href="#">阅览数：{{article.read_count}}</a>
									<a href="#">评论数:{{article.comment_count}}</a>
								</div>
								<div class="right" style="float: right">
									<a href="{% url 'blog:detail'%}?aid={{article.id}}">查看</a>
									<a href="{% url 'blog:delete'%}?aid={{article.id}}">删除</a>

								</div>
							</div>
						</div>

					</div>
				{% empty %}
					<span>当前没有任何文章</span>
				{% endfor %}

            </div>


        </div>
    </div>

</body>
</html>

blogProject/templates/blog/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <link rel="stylesheet" href="../static/css/login.css">

</head>
<body>

    <div style="width: 800px; margin: auto;">
        <h1 style="text-align: center;">欢迎注册</h1>
        <form action="" method="post" style="text-align: center;">
            账号：<input type="text" name="account"><br>
            密码：<input type="text" name="password"><br>
            <input type="submit">
        </form>
        <div style="width: 800px; margin: auto;">
            <a href="/">返回主页</a>
            <a href="/login">用户登录</a>
        </div>
    </div>


</body>
</html>

blogProject/templates/blog/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>更新文章</title>
</head>
<body>
    <div>
        <a href="/">系统首页</a>
        <a href="{% url 'blog:home' %}">我的主页</a>
        <a href="{% url 'blog:register' %}">返回注册</a>
        <a href="{% url 'blog:login' %}">返回登录</a>
    </div>
    <div>
        <form action="" method="post">
            文章内容：<input type="textarea" name="content">
            <input type="submit">
        </form>
    </div>
</body>
</html>